//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

public class editar_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.TextBox txtTitulo;
protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
protected global::System.Web.UI.WebControls.DropDownList ddlCarrera;
protected global::System.Web.UI.WebControls.TextBox txtMateria;
protected global::System.Web.UI.WebControls.Button btnGuardar;
protected global::System.Web.UI.WebControls.Button btnDescartar;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
private void @__RenderContent6(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
object @__o;

#line 1 "C:\Users\zero_\AppData\Local\Temp\4563556EF0B95360A23DD6B6391F733735D0\4\cimatub_\cimatub_\Pantallas\Editar.aspx"
@__o =  ResolveUrl("~/recursos/CSS/videos.css") ;

#line default
#line hidden
}
}
}
